package HomeWork3;
public enum breed {
		BORDER_COLLIE, POODLE, GERMAN_SHEPHERD, GOLDEN_RETRIEVER, DOBERMAN_PINSCHER, SHETLAND_SHEEPDOG,
		LABRADOR_RETRIEVER, PAPILLON, ROTTWEILER, AUSTRALIAN_CATTLE_DOG
	}